name: Rerecord the reported issue

on:
  pull_request:
env:
  RECORD_REPLAY_API_KEY: rwk_yaEG8jo6gcisGHHoMj8SNoOMIHSbT7REuU5E1QnKCiL

jobs:
  preview-branch:
    name: Wait for Vercel Preview Branch
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 960
          check_interval: 60
          environment: ${{ fromJSON('["", "production"]')[github.ref == 'refs/heads/main'] }}
    outputs:
      url: ${{ steps.waitFor200.outputs.url }}
  get-linked-issues:
    name: Get Linked Issues
    runs-on: ubuntu-latest
    steps:
      - name: Get Linked Issues
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
    outputs:
      issues: ${{ steps.linked-issues.outputs.issues }}

  rerecord-issue:
    name: Rerecord the reported issue
    runs-on: ubuntu-latest
    needs: [preview-branch, get-linked-issues]
    timeout-minutes: 10
    steps:
      - name: Print issue
        run: |
          echo "Preview branch URL: ${{ env.PREVIEW_BRANCH_URL }}"
          echo "Issues: ${{ env.ISSUES }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
        env:
          PREVIEW_BRANCH_URL: ${{ needs.preview-branch.outputs.url }}
          ISSUES: ${{ needs.get-linked-issues.outputs.issues }}
